name = "handterm"
source_dir = "/home/mstouffer/repos/handterm-proj/handterm"
test_result_dir = "retros/handterm/test-result-dir"
test_output_dir = "test-output"

[output_paths]
vitest = "test-output/vitest.xml"
playwright = "test-output/playwright.xml"
