name = "example-remote"
repo_under_test_path = "/home/mstouffer/repos/handterm-proj/handterm"
github_remote = "git@github.com:bizkite-co/handterm.git"
github_project_name = "Handterm"
github_project_number = 4
github_project_owner = "bizkite-co"
test_result_dir = "retros/example-remote"
test_output_dir = "test-output"

[output_paths]
vitest = "test-output/vitest.xml"
playwright = "test-output/playwright.xml"
